// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import ClientConditionalSidebar from "@/components/ClientConditionalSidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RedMath",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row">
          <ClientConditionalSidebar>
            {children}
          </ClientConditionalSidebar>
        </div>
      </body>
    </html>
  );
}
